In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
""" 
Feature engineering step
1. FE Starter

Feature, Target column
2. Train Test
3. Missing values handling
4. Outlier detection and handling
5. categorical -> numerical (encoding)
6. Scalling (zscore .... )
7. Feature creation

"""

' \nFeature engineering step\n1. FE Starter\n\nFeature, Target column\n2. Train Test\n3. Missing values handling\n4. Outlier detection and handling\n5. categorical -> numerical (encoding)\n6. Scalling (zscore .... )\n7. Feature creation\n\n'

In [15]:
df = pd.read_csv('titanic_data_updated.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [17]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [18]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [19]:
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         no   third    male  22.0      1      0   7.2500        S
1        yes   first  female  38.0      1      0  71.2833        C
2        yes   third  female  26.0      0      0   7.9250        S
3        yes   first  female  35.0      1      0  53.1000        S
4         no   third    male  35.0      0      0   8.0500        S
..       ...     ...     ...   ...    ...    ...      ...      ...
886       no  second    male  27.0      0      0  13.0000        S
887      yes   first  female  19.0      0      0  30.0000        S
888       no   third  female   NaN      1      2  23.4500        S
889      yes   first    male  26.0      0      0  30.0000        C
890       no   third    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [20]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [21]:
df['Survived']

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object