In [18]:
import pandas as pd
import numpy as np

In [19]:

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})

df

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [23]:
# df['A'].fillna(df['A'].mean())
df['A'].fillna(0)
df

C:\Users\nafiz\AppData\Local\Temp\ipykernel_8568\3478121880.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(0, inplace=True)

   A     B     C
0  0   5.0     a
1  0   NaN     b
2  0   NaN     c
3  0   NaN  None
4  0  10.0     e